name: GraalVM

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  graalvm:
    name: GraalVM
    runs-on: ubuntu-latest
    outputs:
      xoom_version: ${{ steps.version.outputs.xoom_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          java: 'java8'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Determine version
        id: version
        run: echo "::set-output name=xoom_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Install the native-image component
        run: gu install native-image

      - name: Build with GraalVM
        run: mvn --batch-mode -Pgithub-releases -Pnative-image clean install

      - name: Publish GraalVM artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraalVM
          path: |
            target/*.h
            target/*.so
            target/*.build_artifacts.txt

      - name: Notify slack
        if: failure() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && github.repository_owner == 'vlingo'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ci-cd
          SLACK_USERNAME: Bob the Builder
          SLACK_ICON: 'https://vlingo.io/wp-content/uploads/cropped-vlingo-favicon-180x180.png'
          SLACK_FOOTER: 'GraalVM ${{ github.repository }}:${{ steps.version.outputs.xoom_version }}'
